"""Deep inspection tests for the nftables ruleset generated by ttp.firewall."""

import pytest
from unittest.mock import patch, MagicMock
from ttp.firewall import apply_rules

@pytest.fixture
def mocked_firewall():
    with patch("ttp.firewall.pwd.getpwnam") as mock_pwd, \
         patch("ttp.firewall._run_nft_string") as mock_run_string, \
         patch("ttp.firewall._run_nft") as mock_run_nft:
        mock_pwd.return_value = MagicMock(pw_uid=110)
        yield {
            "mock_pwd": mock_pwd,
            "mock_run_string": mock_run_string,
            "mock_run_nft": mock_run_nft
        }

def test_nat_output_chain_ordering(mocked_firewall):
    """Tor exemption MUST be before any redirection in the NAT output chain."""
    apply_rules(tor_user="debian-tor")
    ruleset = mocked_firewall["mock_run_string"].call_args[0][0]
    
    output_block = ruleset.split("chain output")[1].split("}")[0]
    
    # 1. Tor exemption exists
    assert "meta skuid 110 accept" in output_block
    # 2. Redirection exists
    assert "dnat" in output_block
    
    # 3. Exemption is BEFORE dnat
    pos_exempt = output_block.find("meta skuid 110 accept")
    pos_dnat = output_block.find("dnat")
    assert pos_exempt < pos_dnat, "Tor exemption must precede NAT redirection!"

def test_filter_out_chain_completeness(mocked_firewall):
    """Filter chain must contain all safety rules and end with reject."""
    apply_rules(tor_user="debian-tor")
    ruleset = mocked_firewall["mock_run_string"].call_args[0][0]
    
    assert "chain filter_out" in ruleset
    filter_block = ruleset.split("chain filter_out")[1].split("}")[0]
    
    expected_rules = [
        "meta skuid 110 accept",
        "meta skuid 0 accept",
        "ip daddr 127.0.0.0/8 accept",
        "meta nfproto ipv6 drop",
        "reject"
    ]
    
    for rule in expected_rules:
        assert rule in filter_block, f"Missing critical rule in filter_out: {rule}"
        
    # The last rule must be reject
    assert filter_block.strip().endswith("reject"), "Filter chain must end with 'reject' kill-switch"

def test_prerouting_chain_exists(mocked_firewall):
    """Prerouting chain should be present for gateway support."""
    apply_rules(tor_user="debian-tor")
    ruleset = mocked_firewall["mock_run_string"].call_args[0][0]
    
    assert "chain prerouting" in ruleset
    assert "type nat hook prerouting" in ruleset
