"""DNS Management Module - Handles routing DNS queries through Tor.

This module implements a stateless, Kernel-level DNS redirection strategy
using a `mount --bind` overlay on `/etc/resolv.conf`.
"""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import Any
from ttp.exceptions import DNSError

logger = logging.getLogger("ttp")

RESOLV_CONF = Path("/etc/resolv.conf")
RUNTIME_RESOLV = Path("/run/ttp/resolv.conf")


def detect_active_interface() -> str:
    """Detect the primary network interface using 'ip route'."""
    try:
        result = subprocess.run(
            ["ip", "route", "show", "default"],
            capture_output=True,
            text=True,
            check=True,
        )
        # Output example: "default via 192.168.1.1 dev eth0 proto dhcp..."
        parts = result.stdout.split()
        if "dev" in parts:
            return parts[parts.index("dev") + 1]
    except (subprocess.CalledProcessError, IndexError):
        pass
    return "eth0"  # Sane fallback if detection fails


def _is_mount_point(target: str) -> bool:
    """Check if *target* is an active mount point by inspecting ``/proc/mounts``."""
    try:
        with open("/proc/mounts", "r") as f:
            for line in f:
                parts = line.split()
                if len(parts) >= 2 and parts[1] == target:
                    return True
    except OSError:
        pass
    return False


def _clear_stale_mounts(target: str) -> None:
    """Iteratively unmount all stacked overlays on *target*.

    Keeps calling ``umount -l`` until the path is no longer listed
    in ``/proc/mounts``.  A safety limit of 10 iterations prevents
    infinite loops.
    """
    for i in range(10):
        if not _is_mount_point(target):
            return
        logger.debug("Removing stale mount layer %d on %s", i + 1, target)
        subprocess.run(
            ["umount", "-l", target],
            capture_output=True,
            text=True,
            check=False,
        )

    if _is_mount_point(target):
        logger.warning(
            "Could not fully clear stale mounts on %s after 10 attempts", target
        )


def apply_dns(interface: str) -> dict[str, Any]:
    """Apply Tor DNS settings using a Kernel-level overlay (mount --bind).

    Returns a dictionary containing backup data for restoration.
    """
    try:
        from ttp.tor_detect import is_ipv6_supported

        nameservers = "nameserver 127.0.0.1\n"
        if is_ipv6_supported():
            nameservers += "nameserver ::1\n"

        # 1. Write the Tor resolver to /run/ttp/resolv.conf (volatile)
        RUNTIME_RESOLV.write_text(
            f"# Generated by TTP\n{nameservers}", encoding="utf-8"
        )

        # 2. Symlink check: resolve the real target for mount --bind
        target = RESOLV_CONF
        if os.path.islink(str(RESOLV_CONF)):
            target = Path(os.path.realpath(str(RESOLV_CONF)))

        # 3. Clear any stale mount stacks (idempotency guard)
        _clear_stale_mounts(str(target))

        # 4. Overlay via mount --bind (non-destructive)
        subprocess.run(
            ["mount", "--bind", str(RUNTIME_RESOLV), str(target)],
            capture_output=True,
            text=True,
            check=True,
        )

        return {"mode": "overlay", "mount_target": str(target)}
    except subprocess.CalledProcessError as e:
        raise DNSError(f"mount --bind failed: {e.stderr.strip()}") from e
    except OSError as e:
        raise DNSError(f"Failed to write runtime resolv.conf: {e}") from e


def restore_dns(backup: dict[str, Any] | None) -> None:
    """Restore original system DNS settings by unmounting the overlay."""
    if not backup:
        return

    mount_target = backup.get("mount_target", str(RESOLV_CONF))

    if _is_mount_point(mount_target):
        try:
            # Lazy unmount ensures immediate release even if busy
            subprocess.run(
                ["umount", "-l", mount_target],
                capture_output=True,
                text=True,
                check=True,
            )
            logger.info("Successfully unmounted DNS overlay on %s", mount_target)
        except subprocess.CalledProcessError as e:
            err_msg = e.stderr.strip() if e.stderr else str(e)
            logger.warning(
                "Failed to unmount DNS overlay on %s: %s", mount_target, err_msg
            )
    else:
        logger.debug("DNS target %s is not mounted, skipping unmount", mount_target)

    # Cleanup the ephemeral file to free tmpfs space
    try:
        if RUNTIME_RESOLV.exists():
            RUNTIME_RESOLV.unlink()
    except OSError as e:
        logger.debug("Failed to remove runtime resolv.conf: %s", e)
