"""DNS Management Module — Handles routing DNS queries through Tor.

Supports two main modes:
1. systemd-resolved: Uses resolvectl to dynamically update interface settings.
2. resolv.conf: Directly modifies /etc/resolv.conf for legacy/minimal systems.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any
from ttp.exceptions import DNSError

RESOLV_CONF = Path("/etc/resolv.conf")


def detect_dns_mode() -> str:
    """Detect if the system uses systemd-resolved or standard resolv.conf."""
    try:
        # Check if systemd-resolved is active and reachable via systemctl
        subprocess.run(
            ["systemctl", "is-active", "--quiet", "systemd-resolved"], check=True
        )
        return "resolvectl"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "resolv.conf"


def detect_active_interface() -> str:
    """Detect the primary network interface using 'ip route'."""
    try:
        result = subprocess.run(
            ["ip", "route", "show", "default"],
            capture_output=True,
            text=True,
            check=True,
        )
        # Output example: "default via 192.168.1.1 dev eth0 proto dhcp..."
        parts = result.stdout.split()
        if "dev" in parts:
            return parts[parts.index("dev") + 1]
    except (subprocess.CalledProcessError, IndexError):
        pass
    return "eth0"  # Sane fallback if detection fails


def apply_dns(mode: str, interface: str) -> dict[str, Any]:
    """Apply Tor DNS settings based on the detected mode.

    Returns a dictionary containing backup data for restoration.
    """
    if mode == "resolvectl":
        try:
            # 1. Point DNS to Tor's DNSPort (127.0.0.1:9053)
            subprocess.run(
                ["resolvectl", "dns", interface, "127.0.0.1"],
                capture_output=True,
                text=True,
                check=True,
            )
            # 2. Set global routing domain (~.) to intercept all traffic
            subprocess.run(
                ["resolvectl", "domain", interface, "~."],
                capture_output=True,
                text=True,
                check=True,
            )
            # 3. Flush caches to force immediate effect
            subprocess.run(["resolvectl", "flush-caches"], check=False)

            return {"mode": "resolvectl", "interface": interface}
        except subprocess.CalledProcessError as e:
            raise DNSError(f"resolvectl failed: {e.stderr.strip()}") from e

    else:
        # Legacy resolv.conf mode
        try:
            original_content = RESOLV_CONF.read_text(encoding="utf-8")
        except OSError:
            original_content = "nameserver 1.1.1.1\n"  # Emergency default

        new_content = "# Generated by TTP\nnameserver 127.0.0.1\n"
        try:
            RESOLV_CONF.write_text(new_content, encoding="utf-8")
            return {"mode": "resolv.conf", "original_content": original_content}
        except OSError as e:
            raise DNSError(f"Failed to modify /etc/resolv.conf: {e}") from e


def restore_dns(mode: str, backup: Any) -> None:
    """Restore original system DNS settings using a Hard-Reset strategy."""
    if not backup:
        return

    if mode == "resolvectl":
        interface = (
            backup.get("interface", "eth0") if isinstance(backup, dict) else "eth0"
        )
        try:
            # Hard-Reset Strategy: Revert -> Restart -> Flush
            # 1. Perform a soft revert on the specific interface
            subprocess.run(["resolvectl", "revert", interface], check=False)

            # 2. Force-restart the daemon to purge any lingering state
            subprocess.run(["systemctl", "restart", "systemd-resolved"], check=False)

            # 3. Clear all caches
            subprocess.run(["resolvectl", "flush-caches"], check=False)

        except Exception as e:
            # We use a broad catch here because network restoration is critical
            raise DNSError(f"Failed to hard-reset DNS: {e}") from e
    else:
        # resolv.conf mode — restore original file content
        original = ""
        if isinstance(backup, dict):
            original = backup.get("original_content", "")
        elif isinstance(backup, str):
            original = backup

        if original:
            try:
                RESOLV_CONF.write_text(original, encoding="utf-8")
            except OSError as e:
                raise DNSError(f"Failed to restore /etc/resolv.conf: {e}") from e
