#!/bin/bash
# ══════════════════════════════════════════════════════════════════════
# TTP — Universal Installer
# ══════════════════════════════════════════════════════════════════════
#
# This script deploys TTP system-wide on any Linux distribution.
# It is the recommended installation method for end users who clone
# the repository directly (as opposed to installing via .deb or .rpm).
#
# Installation strategy:
#   1. Copy source files to /opt/ttp (standard location for third-party
#      software on Linux, avoids conflicts with system packages).
#   2. Create an isolated Python virtual environment at /opt/ttp/venv.
#      This bypasses PEP 668 restrictions on modern distros that block
#      system-wide pip installs (e.g., Debian 12+, Fedora 38+).
#   3. Symlink the 'ttp' binary to /usr/local/bin so it's available
#      globally without modifying PATH.
#   4. On Fedora/RHEL: compile and install a custom SELinux policy
#      module from the .te source file, allowing Tor to bind to the
#      non-standard ports TTP requires (9040, 9053).
#
# Usage:
#   sudo ./scripts/install.sh
#
# To uninstall:
#   sudo ./scripts/uninstall.sh
# ══════════════════════════════════════════════════════════════════════

# Ensure the script is run as root, as we need to modify system directories.
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run as root (use: sudo ./scripts/install.sh)"
  exit 1
fi

echo "[TTP] Starting system-wide installation..."

# 1. System Deployment
# We use /opt/ttp as the primary home for the application logic and assets.
# This follows Linux best practices for optional/third-party software.
echo "[TTP] Deploying files to /opt/ttp..."
mkdir -p /opt/ttp
cp -r ttp /opt/ttp/
cp -r assets /opt/ttp/
cp pyproject.toml /opt/ttp/
cp README.md /opt/ttp/

# 2. Dependency Management
# We use a virtual environment to avoid polluting system packages and bypass PEP 668.
# We install the package in editable mode or normally into the venv.
echo "[TTP] Setting up virtual environment and dependencies..."
if ! python3 -m venv /opt/ttp/venv >/dev/null 2>&1; then
    echo "Error: 'python3-venv' is missing. Please install it (e.g., sudo apt install python3-venv)"
    exit 1
fi

/opt/ttp/venv/bin/pip install --upgrade pip >/dev/null 2>&1
/opt/ttp/venv/bin/pip install /opt/ttp/ >/dev/null 2>&1

# 3. Global Command Creation
# We link to the 'ttp' executable generated by pip inside the virtual environment.
echo "[TTP] Creating global 'ttp' command..."
ln -sf /opt/ttp/venv/bin/ttp /usr/local/bin/ttp

# 4. SELinux Optimization (Fedora/RHEL/CentOS Family)
# On Red Hat-based systems, SELinux often blocks Tor from binding to non-standard ports.
# We compile and install a custom policy module from source to allow this interaction.
if command -v getenforce >/dev/null 2>&1; then
    if [ "$(getenforce)" = "Enforcing" ]; then
        echo "[TTP] SELinux Enforcing mode detected."
        
        # We only install the module if it's not already there.
        if ! semodule -l | grep -q "ttp_tor_policy"; then
            echo "[TTP] Compiling and optimizing kernel policies..."
            if ! command -v checkmodule >/dev/null 2>&1; then
                echo "[TTP] SELinux build tools missing. Attempting to install 'checkpolicy'..."
                dnf install -y checkpolicy policycoreutils >/dev/null 2>&1 || echo "[TTP] Failed to install checkpolicy. Tor might fail to start."
            fi
            
            if command -v checkmodule >/dev/null 2>&1; then
                (
                    cd /opt/ttp/ttp/resources/selinux || exit 1
                    checkmodule -M -m -o ttp_tor_policy.mod ttp_tor_policy.te
                    semodule_package -o ttp_tor_policy.pp -m ttp_tor_policy.mod
                    semodule -i ttp_tor_policy.pp
                    echo "[TTP] SELinux module 'ttp_tor_policy' compiled and installed successfully."
                )
            fi
        else
            echo "[TTP] SELinux module already present. Skipping."
        fi
    fi
fi

echo "[TTP] Installation complete! You can now use 'sudo ttp start' to begin."

# One-time discrete message to encourage GitHub stars.
echo ""
echo "Thanks for using TTP! Starring the repo on GitHub helps the project grow."
mkdir -p /var/lib/ttp
touch /var/lib/ttp/.starred_notified