# Copyright (c) 2026 onyks-os
# SPDX-License-Identifier: MIT

"""Validation and guard utilities for the TTP CLI.

Contains input validators (bridge lines, IPv4 addresses), runtime guards
(root check, systemd check), and the high-level ``verify_tor()`` helper
that drives the bootstrap progress UI.
"""

from __future__ import annotations

import os
import re
import time

import typer
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TaskProgressColumn,
    TextColumn,
)

from ttp.exceptions import TorError

# A bridge value becomes exactly one physical line of the generated torrc.
# str.split() treats \n, \r, \v, \f, \x1c-\x1e, \x85, \u2028 and \u2029 as
# ordinary whitespace, so a multi-line value would tokenise cleanly here and
# then turn into several torrc directives at the writer. Refuse anything
# outside printable ASCII (tab tolerated) before tokenising.
_BRIDGE_ILLEGAL_CHARS = re.compile(r"[^\x20-\x7e\t]")


def validate_bridge_line(line: str) -> None:
    """Perform basic format validation on a bridge configuration line."""
    if _BRIDGE_ILLEGAL_CHARS.search(line):
        raise ValueError(
            "A bridge line must be a single line of printable ASCII. "
            "To configure several bridges, repeat --bridge once per line "
            "or pass them with --bridge-file."
        )

    parts = line.split()
    if not parts:
        raise ValueError("Empty bridge line")

    if ":" in parts[0]:
        return

    if len(parts) >= 2 and ":" in parts[1]:
        first_word = parts[0].lower()
        if first_word in {"obfs4", "snowflake", "meek", "meek_lite"}:
            return
        raise ValueError(f"Unsupported pluggable transport: '{parts[0]}'")

    raise ValueError("Invalid bridge format. Expected '<ip>:<port>' or '<transport> <ip>:<port>'")


def require_root() -> None:
    """Exit with an error if the process is not running as root."""
    from ttp.commands._common import print_error

    if os.geteuid() != 0:
        print_error("Permission Denied", "This command must be run as root (use sudo).")
        raise typer.Exit(code=1)


def require_root_or_watchdog_user() -> None:
    """Allow the watchdog daemon entrypoint to run as root or as ttp-watchdog.

    The volatile unit generated by ttp.watchdog.service drops to the
    ``ttp-watchdog`` account whenever packaging created it, so a bare
    ``euid == 0`` check makes the daemon unstartable. The guard is narrowed,
    not removed: an arbitrary unprivileged user still cannot run
    ``ttp watchdog run`` by hand and drive the FSM's auto-heal and killswitch
    paths.
    """
    import pwd

    from ttp.commands._common import print_error

    euid = os.geteuid()
    if euid == 0:
        return
    try:
        if euid == pwd.getpwnam("ttp-watchdog").pw_uid:
            return
    except KeyError:
        pass

    print_error(
        "Permission Denied",
        "This command must be run as root or as the 'ttp-watchdog' service account.",
    )
    raise typer.Exit(code=1)


def require_systemd() -> None:
    """Exit if systemd runtime directory is not present."""
    from ttp.commands._common import print_error

    if not os.path.exists("/run/systemd/system"):
        print_error("Systemd Required", "TTP explicitly requires systemd.")
        raise typer.Exit(code=1)


def verify_tor(timeout: int = 180) -> tuple[bool, str]:
    """Verify that traffic is routed through Tor, with bootstrap progress UI."""
    from ttp import tor_control
    from ttp.commands._common import _PREFIX, console, print_error

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
        transient=True,
    ) as progress:
        task_id = progress.add_task(f"{_PREFIX} Waiting for Tor to bootstrap...", total=100)

        try:
            tor_control.wait_for_bootstrap(
                progress_callback=lambda val: progress.update(task_id, completed=val),
                timeout=timeout,
            )
            progress.stop()
            console.print(f"{_PREFIX} Tor is 100% bootstrapped.")
        except (TorError, RuntimeError) as e:
            progress.stop()
            print_error("Bootstrap Error", str(e))
            return False, "unknown"

    time.sleep(2)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task(f"{_PREFIX} Verifying Tor routing...", total=None)
        return tor_control.verify_tor()


def parse_txt_dig_ipv4(dig_stdout: str) -> str | None:
    """Return the first plausible IPv4 from ``dig +short TXT`` output."""
    for raw_line in dig_stdout.strip().splitlines():
        line = raw_line.strip().strip('"').strip("'").strip()
        if not line:
            continue
        if re.match(r"^(\d{1,3}\.){3}\d{1,3}$", line):
            return line
        m = re.search(r"\b(\d{1,3}(?:\.\d{1,3}){3})\b", line)
        if m:
            return m.group(1)
    return None
