#!/usr/bin/env python3
# Copyright (c) 2026 onyks-os
# SPDX-License-Identifier: MIT
"""Regenerate packaging/build-requirements.txt for a given hatchling version.

    python3 packaging/pin_build_backend.py 1.32.4

Resolves hatchling, the `build` frontend and their dependencies in a throwaway
venv, then writes every one of them with the SHA-256 of each wheel PyPI
publishes for that version.
Stdlib only, so it runs before anything is installed. Review the diff it
produces like any other dependency update: it decides what builds the release.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import urllib.request
import venv
from pathlib import Path

OUT = Path(__file__).resolve().parent / "build-requirements.txt"

# Needed by hatchling only on Python < 3.11; the release builds on newer, but a
# local build on 3.10 must still resolve it under the same constraints.
CONDITIONAL = ["tomli"]

HEADER = """\
# Copyright (c) 2026 onyks-os
# SPDX-License-Identifier: MIT
#
# The exact build environment of every TTP artifact: the build frontend
# (build), the backend (hatchling) and everything they pull in, each pinned to
# one version and to the SHA-256 of the files PyPI serves for it. pip enforces
# the hashes (--require-hashes), so a different file under the same version
# fails the build instead of producing a different artifact.
#
# Installed by packaging/build_python.sh, which release.sh, build_deb.sh and the
# rpm spec all build through. pyproject.toml keeps a floor (hatchling>=1.27) so
# that downstream packagers can build with their own hatchling; this file is
# what TTP's own releases are built with.
#
# Generated by: python3 packaging/pin_build_backend.py {version}
"""


def _pypi(name: str, version: str | None = None) -> dict:
    url = f"https://pypi.org/pypi/{name}/{version}/json" if version else f"https://pypi.org/pypi/{name}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def _resolve(hatchling_version: str) -> dict[str, str]:
    with tempfile.TemporaryDirectory() as tmp:
        venv.create(tmp, with_pip=True)
        py = Path(tmp) / "bin" / "python"
        subprocess.run([py, "-m", "pip", "install", "-q", f"hatchling=={hatchling_version}", "build"], check=True)
        frozen = subprocess.run([py, "-m", "pip", "freeze"], check=True, capture_output=True, text=True).stdout
    pins = dict(line.split("==", 1) for line in frozen.splitlines() if "==" in line)
    for name in CONDITIONAL:
        pins.setdefault(name, _pypi(name)["info"]["version"])
    return pins


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    version = sys.argv[1]
    lines = [HEADER.format(version=version)]
    for name, pinned in sorted(_resolve(version).items(), key=lambda item: item[0].lower()):
        release = _pypi(name, pinned)
        hashes = sorted(u["digests"]["sha256"] for u in release["urls"] if u["filename"].endswith(".whl"))
        if not hashes:
            raise SystemExit(f"{name}=={pinned} has no wheel on PyPI; refusing to pin an sdist build")
        wrapped = " \\\n    ".join(f"--hash=sha256:{h}" for h in hashes)
        lines.append(f"{release['info']['name'].lower()}=={pinned} \\\n    {wrapped}\n")
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
